# Generated by Django 2.0.3 on 2018-04-07 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RummyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.TextField(choices=[('Hearts', 'Hearts'), ('Diamonds', 'Diamonds'), ('Clubs', 'Clubs'), ('Spades', 'Spades')])),
                ('rank', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13)])),
            ],
        ),
        migrations.CreateModel(
            name='RummyGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', game.models.DeckField()),
                ('current_card', game.models.CardField()),
            ],
        ),
        migrations.CreateModel(
            name='RummyPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', game.models.HandField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rummygame',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='game.RummyPlayer'),
        ),
        migrations.AddField(
            model_name='rummygame',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='game.RummyPlayer'),
        ),
        migrations.AddField(
            model_name='rummygame',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn', to='game.RummyPlayer'),
        ),
        migrations.AddField(
            model_name='rummygame',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='game.RummyPlayer'),
        ),
    ]
