# Generated by Django 2.0.3 on 2018-04-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20180408_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RummyCard',
        ),
    ]
