# Generated by Django 2.0.3 on 2018-04-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_delete_rummycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='rummygame',
            name='melds',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rummygame',
            name='current_card',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rummygame',
            name='deck',
            field=models.TextField(default=''),
        ),
    ]
