# Generated by Django 2.0.3 on 2018-04-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180415_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('draw_option', models.TextField(choices=[('top_of_deck_card', 'top_of_deck_card'), ('current_card', 'current_card')])),
                ('draw_card', models.TextField(default='')),
                ('meld_option', models.TextField(choices=[('play_meld', 'play_meld'), ('lay_off', 'lay_off'), ('continue_to_discard', 'continue_to_discard')])),
                ('meld_cards', models.TextField(default='')),
                ('discard_card', models.TextField(default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.RummyGame')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.RummyPlayer')),
            ],
        ),
    ]
