# Generated by Django 2.0.3 on 2018-04-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.RummyGame')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_loser', to='game.RummyPlayer')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='game.RummyPlayer')),
            ],
        ),
    ]
